data_subdir: data
processor:
  class: MultiTaskProvider
  module: experimenter.data.MultiTaskProvider
  params:
    loaders:
    - class: Dummy
      module: experimenter.loaders.Dummy
      params:
        cls_label: label
        data_size: 1000
        lm_label: lm
    down_weight_classes: false
    task_order:
    - 0
    batch_size: 4
    drop_last: true
    input_path: ''
    label_encoder:
    - text
    - class
    label_indx:
      label: 1
      lm: 0
    mask_weights:
    - 1
    - 1
    max_vocab_size: 3000
    min_vocab_count: 10
    separator: ' '
    seq_len:
      inp:
      - 20
      label:
      - 20
      - 1
      mask:
      - 1
      - 1
    shuffle: true
    splits:
    - 0.7
    - 0.2
    - 0.1