data_subdir: data
processor:
  class: MultiTaskProvider
  module: experimenter.data.MultiTaskProvider
  params:
    loaders:
    - class: MovieCorpus
      module: experimenter.loaders.MovieCorpus
      params:
        label_col: response
        limit: 1000 
        input_paths:
            - "cornell movie-dialogs corpus"
    task_order:
    - 0
    batch_size: 4
    down_weight_classes: false
    drop_last: true
    input_path: ''
    label_encoder:
    - text
    label_indx:
      response: 0
    mask_weights:
    - 1
    seq_len:
      inp:
      - 20
      label:
      - 20
      mask:
      - 1
    shuffle: true
    splits:
    - 0.7
    - 0.2
    - 0.1
