# A workflow to check code style and run pytest that runs on PR
name: PR checks

# When to run the workflow. 
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install black flake8 isort pytest
          pip install -r requirements.txt
      
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true
          isort: true
      
      - name: Run Pytest
        run:
          python -m pytest tests
      
